title: Bugatsinho Repository
author: bugatsinho
description: > # this means to ignore newlines until "baseurl:"
  Here you can find my 3rd party add-ons and repository for Kodi!
  Feel free to open an issue if something wrong with them!
  [Repository v2.1](https://github.com/bugatsinho/bugatsinho.github.io/blob/master/repository.bugatsinho-2.1.zip)
  [Add-ons](https://github.com/bugatsinho/bugatsinho.github.io/blob/master/)
# social links
twitter_username: https://twitter.com/bugatsinho

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
